spring.application.name=api

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=rm572867
spring.datasource.password=141107
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
server.port=8080